#!/bin/bash

export LD_LIBRARY_PATH=.
export PATH=$PATH:.

[[ ! $FPS ]] && FPS=15
[[ ! $QUALITY ]] && QUALITY=0
[[ ! $SCREEN_RES ]] && SCREEN_RES="-s 1920x1080"
SOURCE=".screencap.avi"

rm $SOURCE
mkfifo $SOURCE

videosource "$SOURCE" $@ &

avconv \
	-vsync 1 -async 1 \
	$AUDIO_DEVICE \
	-f x11grab $SCREEN_RES -r $FPS -i :0.0 \
	-qscale $QUALITY \
	-y "$SOURCE" -v 0 \
#> /dev/null # we don't want to screw with the output...

wait
